# Generated by Django 3.0 on 2021-04-06 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('multiple', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='topic',
            field=models.CharField(default='None', max_length=100),
        ),
    ]
